### ISSUE TITLE
base <4.8.0.0 constraint prevents building with GHC 7.10.1-rc1

### ISSUE THREAD

**Issue by peti** [massysett/barecheck#1]
I would like to use cartel with GHC 7.10.1, but I can't unfortunately, because the dependency constraint of this package prevents me from building it with that compiler. Would you mind editing the Cabal file on Hackage to allow version 4.8.x of `base` as a build input?

**Comment by massysett** [comment]
I'd rather wait until they release 7.10 so I can compile and test it, sorry.  Shouldn't --allow-newer help with this?

**Comment by peti** [comment]
Duh, I work with unreleased versions of GHC all the time. If it's your policy to prevent your users from easily installing the library in such an environment, then I cannot use it and will give up on Cartel.

**Comment by massysett** [comment]
So you're saying that --allow-newer doesn't help?  Go ahead and fork or give up, but Haskell moves fast enough without trying to hit the moving target of a GHC RC.  Looks like they haven't even sorted out some huge changes to the Prelude.

**Comment by peti** [comment]
> Go ahead and fork or give up.

Okay then, will do. Thank you for your help.

**Comment by FranklinChen** [comment]
GHC 7.10.1 is out now.

```console
$ cabal install barecheck
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: barecheck-0.2.0.8 (user goal)
next goal: base (dependency of barecheck-0.2.0.8)
rejecting: base-4.8.0.0/installed-901... (conflict: barecheck => base>=4.5.0.0
&& <4.8.0.0)
rejecting: base-4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0,
4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0,
4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed
instance)
```

**Comment by massysett** [comment]
I have stopped maintaining this package.  I will add a note to the
README.md explaining why.
